### ISSUE TITLE
IBM Milestone 2: IPMI 2.0:  SDR test and automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1181]
Development epic: https://github.com/openbmc/openbmc/issues/2610

- [ ] IPMI 2.0 SDR - Test plan 

- [ ] IPMI 2.0 SDR  Automation 

- [ ] IPMI 2.0 SDR  Testing
