### ISSUE TITLE
IBM Milestone 2: Webui Manual and automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1183]
Development Epic: https://github.com/openbmc/openbmc/issues/2638

- [ ] Manual Test of WebUI

- [ ] Test Plan Preparation - @samahaba 

- [ ] Automation Test - Sivas @samahaba and any other folks interested

**Comment by sivassrr** [comment]
Done and automated vital TCs
