### ISSUE TITLE
SNMP Test:

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1373]
- [ ] SNMP Test Plan

- [ ] SNMP Test Execution

- [ ] SNMP Automation - Good Path all, important bad path

Corresponding development issues to be look at is
https://github.com/openbmc/openbmc/issues/2800
