### ISSUE TITLE
GUI: Code update via TFTP way

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1396]
- [ ] Assign global variable for TFTP and directory location if needed

- [ ] Code update test cases via TFTP good path

- [ ] Code update test cases via TFTP bad path
