### ISSUE TITLE
Redfish Certificate Test and automation

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1501]
- [x] Test plan
- [x] Test and verify
- [x] Automation

CSR + Upload + View + others

**Comment by rahulmah** [comment]
### Test plan: Certificate Testing


### Good Path
- [ ] Verify server certificate view via Redfish
1. Install valid https server certificate via Redfish.
2. Verify installed certificate via Redfish's view server certificate.

- [ ] Verify server certificate view via Openssl
1. Install valid https server certificate via Redfish
2. Verify installed certificate has been uploaded via openssl tool.
openssl s_client -connect <BMC_IP>:443 -showcerts


- [ ] Verify client certificate view via Redfish
1. Install valid ldap client certificate via Redfish.
2. Verify installed certificate via Redfish's view client certificate.


- [ ] Verify CA certificate view via Redfish
1. Install valid CA certificate via Redfish.
2. Verify installed certificate via Redfish's view CA certificate.


- [ ] Verify replace server certificate via Redfish
1. Install valid server certificate via Redfish.
2. Replace server certificate via Redfish.
3. Verify replaced certificate via Redfish's view server certificate.


- [ ] Verify replace client certificate via Redfish
1. Install valid client certificate via Redfish.
2. Replace client certificate via Redfish.
3. Verify replaced certificate via Redfish's view client certificate.


- [ ] Verify replace CA certificate via Redfish
1. Install valid CA certificate via Redfish.
2. Replace CA certificate via Redfish.
3. Verify replaced certificate via Redfish's view CA certificate.

- [ ] Verify Generate CSR via Redfish
1. Generate CSR via Redfish.
2. Verify generated CSR via Redfish.


- [ ] Test not yet valid https server certificate install
1. Install not yet valid https server certificate via Redfish 
2. Verify using Redfish view certificate that server certificate is uploaded in BMC.
openssl s_client -connect <BMC_IP>:443 -showcerts


- [ ] Test not yet valid ldap client certificate install
1. Install not yet valid ldap client certificate via Redfish
2. Verify using Redfish view certificate that client certificate is uploaded in BMC



- [ ] Test certificate persistence after BMC code update.
1. Install valid https server and ldap client certificate via Redfish
2. Perform BMC code update. 
3. Verify certificate persistency after code update.


- [ ] Test certificate clean up after factory reset.
1. Install valid https server and ldap client certificate via Redfish
2. Perform factory reset. 
3. Verify that the installed certificates are not present after factory reset.


- [ ] End to end verification of ldap client certificate verification
1. Install client and CA certificate on BMC and create secure CA config.
2. Now check if we are able to login to BMC via secure path(ldaps). Authentication should pass here.


- [ ] End to end verification of ldap client expired certificate verification
1. Install expired client and valid CA certificate on BMC and create secure CA config.
2. Now check if we are able to login to BMC via secure path(ldaps). Authentication should fail here.


- [ ] CA certificate upload of server certificate verification
1. Install CA certificate for https server on BMC.
2. Now verify trusted mark in OpenBMC GUI and other certificate details




### Bad Path

- [ ] Test invalid https server certificate install
1. Install invalid https server certificate(empty private key, empty certificate, invalid private key, corrupted certificate, invalid format) via Redfish
2. Verify error while installing invalid https server certificate.


- [ ] Test invalid ldap client certificate install
1. Install invalid ldap client certificate(empty private key, empty certificate, invalid private key, corrupted certificate, invalid format) via Redfish `xyz/openbmc_project/certs/client/ldap`
2. Verify error while installing invalid certificate.


- [ ] Test client CA certificate install with Empty certificate
1. Install invalid ldap client CA certificate(with empty certificate) via REST /xyz/openbmc_project/certs/authority/ldap 
2. Verify error while installing empty certificate.


- [ ] Test expired https server certificate install
1. Install expired https server certificate via Redfish `xyz/openbmc_project/certs/server/https`
2. Verify error while installing expired certificate..


- [ ] Test expired ldap client certificate install
1. Install expired ldap client certificate via Redfish.
2. Verify error while installing expired certificate.

**Comment by rahulmah** [comment]
@ojayanth @devenrao : Here is the initial test plan for testing redfish certificate changes. Please review it and provide your inputs.

**Comment by devenrao** [comment]
Review comments
) Need to verify Required/Optional arguments for ReplaceCertificate, GenerateCSR
2) After a factory reset bmcweb autogeneates as self signed certificate, verify that phosphor-certificate-manager shows that certificate
3)  Verify replace server certificate via Redfish - this item is duplicate
4) Some cases install and replace are duplicated
