### ISSUE TITLE
GUI: Update User Mgmt - Execution

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1713]
**GUI User Management Test plan Execution** 

- [ ] Create and verify admin role user via GUI - `Pass`

1. Create an admin role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform admin privilege task.

- [ ] Create and verify operator role user via GUI `Failed. operator privilege user able to perform admin task also. Seem to be due to - https://github.com/openbmc/bmcweb/issues/62`

1. Create a operator role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform operator privilege task only.

- [ ] Create and verify user role user via GUI - `Failed. user privilege user able to perform admin task also. Seem to be due to - https://github.com/openbmc/bmcweb/issues/62`

1. Create a user role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform user privilege task only.

- [ ] Create and verify callback role user via GUI - `Failed. Callback user able to perform admin task also. Seem to be due to - https://github.com/openbmc/bmcweb/issues/62`

1. Create a callback role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform callback privilege task only.

- [ ] Verify proper error while creating more than max user limit.  - `Failed. No proper error. Getting error "Failed to create new user" while creating 16th user`

1. Create total 15 users with valid name and password via GUI.
2. Now try to create 16th User via GUI.
3. Verify proper error while creating more than more than 15 users.

- [ ] Verify proper error while creating two users with same name - `Failed. No proper error while creating user with same name. Getting standard error i.e. "Failed to create new user"`

1. Create a user with name - "newuser".
2. Now again try to create a user with same name.
3. Verify proper error while creating 2nd user with same name.

- [ ] Delete and verify user via GUI - `Failed. No proper error while logging with deleted user. Getting Server unreachable in the login page below ip address`

1. Create a user using GUI .
2. Verify GUI login using the newly created user.
3. Delete the newly created user via GUI.
4. Verify that the user is successfully deleted. 
5. Verify that the delete user is unable to login.

- [ ] Verify proper error while login GUI with invalid password - `Failed. No proper error while logging with deleted user. Getting Server unreachable in the login page below ip address`

1. Create a user using GUI .
2. Verify proper error while login GUI with the newly created user with invalid password.

- [ ] Verify user properties modification - `Passed`

1. Create a user with any privilege
2. Modify any of the newly created user properties(password , enable , Role )
3. Verify changes are reflected and working as expected.

- [ ] Verify that user accounts and properties are saved through reboots

1. Create a user with any privilege via GUI.
2. Perform system reboot.
3. Verify the user properties after reboot.

- [ ] Verify creating user without enabling it - `Failed. No proper error while logging with disabled user. Getting Server unreachable in the login page below ip address`

1. Create a user without enabling it via GUI
2. Verify login failed with newly created user and proper error while login.
