### ISSUE TITLE
IPMI and Redfish combination for user management - Execution

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1717]
Test cases : 

- [x] Create User via Redfish And Use it using IPMI - `Passed`

1. Create Redfish user with valid name and password.
2. Verify that the newly created user can run IPMI command.
	ipmitool -I lanplus -C 3 -U <newly created user> -P <password for newly created user> -H <BMC_IP> <IPMI cmd>

- [x] Create User via IPMI And Use it using Redfish - `Passed`

1. Create IPMI user with valid name using "set user name" command. Example :
	ipmitool -I lanplus -C 3 -U root -P 0penBmc -H <BMC_IP> user set name <user id> newuser
2. Verify that the newly created user can run Redfish command.

- [x] Update Password via Redfish And Verify Using IPMI - `Passed`

1. Create Redfish user with valid name and password. 
2. Update password using Redish.
3. Verify that the newly created user can run Redfish command with updated password.

- [x] Update Password via IPMI And Verify Using Redfish - `Passed`

1. Create IPMI user with valid name and password. 
2. Update password using IPMI.
3. Verify that the newly created user can run Redfish command with updated password.

- [x] Delete User via Redfish And Verify using IPMI - `Passed`
1. Create Redfish user with valid name and password.
2. Delete the newly created user using Redfish.
3. Verify that the newly created is successfully delete in IPMI.

- [x] Delete User via IPMI And Verify using Redfish - `Passed` 
1. Create IPMI user with valid name using "set user name" command. Example :
ipmitool -I lanplus -C 3 -U root -P 0penBmc -H <BMC_IP> user set name newuser
2. Delete the newly created user using IPMI.
3. Verify that the newly created is successfully delete in Redfish.

- [x] Update user privilege via Redfish And Verify Using IPMI - `Passed`
1. Create Redfish user with valid name and admin privilege.
2. Update the newly created user privilege to Operator using Redish.
2. Verify that new privilege setting is correctly reflected via IPMI.

- [ ] Update user privilege via IPMI And Verify Using Redfish - `Passed`
1. Create IPMI user with valid name and user privilege. 
2. Update the newly created user privilege to admin using IPMI.
3. Verify that new privilege setting is correctly reflected via Redfish.

- [ ] Verify error while creating more than max user limit. `Failed` https://github.com/openbmc/bmcweb/issues/63
1. Create total 15 users with valid name and password via Redfish and IPMI. 
2. Now try to create 16th User vi Redfish.
3. Verify proper error while creating more than more than 15 users.

- [ ] Create User via Redfish With All Groups Except IPMI - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via Redfish.
2. Add the user to part of all groups except IPMI i.e. ssh, redfish, web
3. Verify that the newly created user can not run IPMI command but can run Redfish commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via Redfish With Only IPMI group - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via Redfish.
2. Add the user to part of only IPMI group.
3. Verify that the newly created user can run IPMI command but cannot run IPMI commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via IPMI With All Groups Except IPMI - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via IPMI.
2. Add the user to part of all groups except IPMI i.e. ssh, redfish, web
3. Verify that the newly created user can not run IPMI command but can run Redfish commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via IPMI With Only IPMI group - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via IPMI.
2. Add the user to part of only IPMI group.
3. Verify that the newly created user can run IPMI command but cannot run IPMI commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info
