### ISSUE TITLE
IPMI redfish combination test cases for user group 

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1848]
- [ ] Create User via Redfish With All Groups Except IPMI - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via Redfish.
2. Add the user to part of all groups except IPMI i.e. ssh, redfish, web
3. Verify that the newly created user can not run IPMI command but can run Redfish commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via Redfish With Only IPMI group - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via Redfish.
2. Add the user to part of only IPMI group.
3. Verify that the newly created user can run IPMI command but cannot run IPMI commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via IPMI With All Groups Except IPMI - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via IPMI.
2. Add the user to part of all groups except IPMI i.e. ssh, redfish, web
3. Verify that the newly created user can not run IPMI command but can run Redfish commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

- [ ] Create User via IPMI With Only IPMI group - `Failed` https://github.com/openbmc/bmcweb/issues/64
1. Create user with valid name and password via IPMI.
2. Add the user to part of only IPMI group.
3. Verify that the newly created user can run IPMI command but cannot run IPMI commands.
ipmitool -I lanplus -C 3 -U <username> -P <password> -H <BMC_IP> sel info

**Comment by rahulmah** [comment]
As per dev, this need OEM support. And it would not be there unless there is a real need.

**Comment by gkeishin** [comment]
@ratagupt @rthomaiy FYI
