### ISSUE TITLE
Witherspoon MFG Stage related Test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#197]
https://github.com/openbmc/openbmc/issues/664

**Comment by sivassrr** [comment]
This includes both January and April deliverables.

**Comment by sivassrr** [comment]
Please feel free to change the estimate.

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/297
https://github.com/openbmc/openbmc-test-automation/issues/308

**Comment by sivassrr** [comment]
- [ ] Please list out all TCs associate with it. ( Send via email or put it in internal repo)

- [ ] Evaluate Automation can be done or need manual execution 

- [ ]  Create stories phase wise

- [ ] Create stories for automation and check-in it in internal repo.

**Comment by swe12345** [comment]
Tested the following commands:
- spstate
- power -off
- sptime -timeofday
- sptime -timeofday 20170206180303
- getvpd -sys_mtm
- updatevpd -sys_mtm
- getvpd -inventory
- getvpd -backplane
- mfgconfig -on 000419b9
- mfgconfig -r
- mfgconfig -off ffffffff
- gard -clr all
- spfirmwareconfig-driver
- sptime -ntpconfigured
- sptime -ntpconfigured 0
- sptime -ntpconfigured 1
- spfirmwareconfig -rbotcnt 0
- spfirmwareconfig -rbotcnt 1
- spfirmwareconfig -rbotcnt
- errorlog -l
- errrolog -l -info
- errorlog -d
- errorlog -d -dump
- errorlog -d -dump-all
- errorlog -p
- spconsole -fsp 9.41.166.231
- bootdev
- bootdev setup
- spflashupdate



- chassispower -on
- ledcontrol -t
- ledcontrol -r
- mfgcommand -m vapi -rn
- mfgcommand -m vapi -n
- mfgcommand  -m vapi -s
- mfgcommand  -m vapi -r
- mfgcommand  -m vapi -t
- mfgcommand  -m vapi -f
- mfgcommand  -m vapi -c
- mfgcommand -m char -append -marker XXX
- mfgcommand -m vfs -e
- dump_pstate -occ 0
- dump_pstate -occ 1
- setfrequencypoint FUT
- chassisconfig
- tmgtclient -change_occ_state 03

Defects:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW404969
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW404970
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW403940

**Comment by SrideviRamesh** [comment]
@gkeishin @sivassrr as  I am not testing manufacturing related testcases. you can remove me from assignee....

**Comment by gkeishin** [comment]
Closing tracked differently
