### ISSUE TITLE
MFG driver test and verification

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#385]
The MFG PNOR build are not on master and we still need to test and report MFG bugs/ verify interfaces and other MFG specific related testing..

**Comment by gkeishin** [comment]
Build 594 ( Master build + MFG PNOR )

- [x] No IPMI core dump
- [x] eSEL looking great
- [x] HMON core dump failure still exist (With Brad patch this is no longer seen)
- [x] https://github.com/openbmc/openbmc/issues/1230  (No longer seen)
- [x] https://github.com/openbmc/openbmc/issues/1228  (No longer seen)

**Comment by gkeishin** [comment]
```*** Driver build Test Outlook - Witherspoon 2 sockets ***```

```
`Master build BMC / PNOR Build Test for MFG`

- [x] SYSTEM     : W42 ( Witherspoon - 2 Sockets )
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/597/
- [x] VERSION_ID : v1.99.3-20-g98927fe
- [x] BUILD TIME : 20170301221558
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.14_1.7
        op-build-v1.14-60-g7462097
        buildroot-2016.11-4-g6b9fd80
        skiboot-8c51fda
        hostboot-6966799
        linux-4.9.8-pa8cf74e
        petitboot-v1.4.1-p38036cb
        witherspoon-xml-c75ecc4
        occ-4141b5f
        hostboot-binaries-446c2ea
        capp-ucode-1bb7503
```

`Test Ran`
```
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED   ( 7 ) 
- [x] Poweron IPL test  : PASSED   ( 5 )   (ON/OFF sequence)
- [x] Host OS Booted    : YES
- [x] OS Reboot Test    : NA ( Not fixed )
- [x] CT - poweron      : PASSED ( 153 tests total, 142 passed, 11 failed  - Known issues ) 
          CT Metrics DB : 
- [x] Inventory         : PASSED ( Data populated )
       Data Content     : FAILED ( There is extra spaces in the properties Model - Deepak is looking at it)
                 [Note] : CQ FW665454 for https://github.com/openbmc/openbmc/issues/1169
- [x] eSEL              : PASSED ( eSEL Data populated)
      Persistency       : PASSED 
	  SEL data          : FAILED ( REST Get view shows Addtional data missing - One time failing trying recreate )
                 [Note] : 
- [x] Autoreboot        : NT   ( Known limitation )

- [x] REST Testing      : PASSED   

- [x] Core dumps        : HWMON core dump still exist

Bug Tracker for today :  None 

```

**Comment by gkeishin** [comment]
```
- [x] SYSTEM     : W42 ( Witherspoon - 2 Sockets - 16 DIMMs )
- [x] BUILD_ID   : /esw/san5/umay/910.1714.20170329a/
- [x] VERSION_ID : ibm-v1.99.3-138-g3a2a586-r0
- [x] Kernel     : Linux witherspoon 4.7.10-382872843bb8e7755fddeaaa284a00c640bfc732 #1 Mon Mar 27 14:34:22 CDT 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503
```

```
--== Welcome to Hostboot hostboot-a58f695/hbicore.bin ==--

  4.36784|secure|SecureROM invalid - skipping functionality
 11.87297|ISTEP  6. 5
 12.55656|ISTEP  6. 6
 12.55755|ISTEP  6. 7
 13.62877|HWAS|PRESENT> DIMM[03]=FF00000000000000
 13.62878|HWAS|PRESENT> Proc[05]=C000000000000000
 13.93337|ISTEP  6. 8
 13.98535|SECURE|Security Access Bit> 0x0000000000000000
 13.98536|SECURE|Secure Mode Disable (via Jumper)> 0xC000000000000000
 13.98552|ISTEP  6. 9
 14.62054|ISTEP  6.10
 14.64642|ISTEP  6.11
 14.64728|ISTEP  6.12
 14.95184|ISTEP  7. 2
 16.88511|ISTEP  7. 3
 17.49494|ISTEP  7. 4
 20.17848|ISTEP  7. 5
 20.28083|ISTEP  8. 1
 20.76188|ISTEP  8. 2
 20.81356|ISTEP  8. 3
 20.89118|ISTEP  8. 4
 30.69731|ISTEP  8. 5
 30.72275|ISTEP  8. 6
 30.72580|ISTEP  8. 7
 30.91226|ISTEP  8. 8
 30.93776|ISTEP  8. 9
 31.06457|ISTEP  8.10
 31.06743|ISTEP  8.11
 31.06842|ISTEP  8.12
 31.52560|ISTEP  8.13
 35.20552|ISTEP  8.14
 35.23272|ISTEP  8.15
 35.23455|ISTEP  8.16
 35.49648|ISTEP  8.17
 35.79143|================================================
 35.79144|Error reported by istep (0x1700) PLID 0x90000005
 35.81779|  No valid PCIE IOP configuration found.  All PHBs on the processor will be disabled.
 35.81780|  ModuleId   0x0a MOD_COMPUTE_PCIE_CONFIG_ATTRS
 35.81780|  ReasonCode 0x170e RC_INVALID_CONFIGURATION
 35.81781|  UserData1  Target processor chip's HUID : 0x00050001002d0004
 35.81782|  UserData2  Target PEC HUID : 0x0000000000000000
 35.84295|------------------------------------------------
 35.84296|  Callout type             : Procedure Callout
 35.84296|  Procedure                : EPUB_PRC_HB_CODE
 35.84297|  Priority                 : SRCI_PRIORITY_HIGH
 35.84299|------------------------------------------------
 35.84299|  Hostboot Build ID: hostboot-a58f695/hbicore.bin
 35.84300|================================================
 61.90838|ISTEP  8.18
 61.91069|ISTEP  8.19
 61.92484|ISTEP  8.20
 61.93340|ISTEP  9. 1
 62.05917|ISTEP  9. 2
 63.14738|ISTEP  9. 3
 63.17289|ISTEP  9. 4
 63.51738|ISTEP  9. 5
 63.54331|ISTEP  9. 6
 63.59650|ISTEP  9. 7
 63.68623|ISTEP  9. 8
 63.71716|ISTEP 10. 1
 64.29408|ISTEP 10. 2
 64.44359|================================================
 64.44360|Error reported by i2c (0x0700) PLID 0x90000006
 64.46948|  Timed out waiting for command complete.
 64.46948|  ModuleId   0x05 I2C_WAIT_FOR_CMD_COMP
 64.46949|  ReasonCode 0x0705 I2C_CMD_COMP_TIMEOUT
 64.49603|  UserData1  Status Register Value : 0x0001000000050001
 64.49604|  UserData2  Master Target : 0x0200ffff0190004d
 64.49604|------------------------------------------------
 64.49605|  Callout type             : Hardware Callout
 64.49606|  CPU id                   : 18
 64.49607|  Target                   : Physical:/Sys0/Node0/Proc1
 64.49608|  Deconfig State           : NO_DECONFIG
 64.49609|  GARD Error Type          : GARD_NULL
 64.49610|  Priority                 : SRCI_PRIORITY_HIGH
 64.49611|------------------------------------------------
 64.49611|  Callout type             : Procedure Callout
 64.49612|  Procedure                : EPUB_PRC_HB_CODE
 64.49613|  Priority                 : SRCI_PRIORITY_LOW
 64.49614|------------------------------------------------
 64.49615|  Hostboot Build ID: hostboot-a58f695/hbicore.bin
 64.49616|================================================
 68.08638|ISTEP 10. 3
 68.37006|ISTEP 11. 1
 68.44759|ISTEP 12. 1
 68.49973|ISTEP 13. 1
 69.61797|ISTEP 13. 2
 69.85061|ISTEP 13. 3
 70.07383|ISTEP 13. 4
 70.14568|ISTEP 13. 6
 70.37337|ISTEP 13. 7
 70.37475|ISTEP 13. 8
 72.57990|ISTEP 13. 9
 73.06168|ISTEP 13.10
 74.35700|ISTEP 13.11
 74.86970|ISTEP 13.12
 74.87436|ISTEP 13.13
 75.08740|ISTEP 14. 1
123.59144|ISTEP 14. 2
123.67363|ISTEP 14. 3
123.75695|ISTEP 14. 4
123.75937|ISTEP 14. 5
124.07083|ISTEP 14. 6
124.09931|ISTEP 14. 7
124.10468|ISTEP 15. 1
127.11431|ISTEP 15. 2
127.11682|ISTEP 15. 3
127.17477|ISTEP 15. 4
127.33412|ISTEP 16. 1
  0.03084|ISTEP 16. 2
128.92017|ISTEP 16. 3
128.95616|ISTEP 16. 4
129.01000|ISTEP 16. 5
129.00892|ISTEP 18.11
129.29996|ISTEP 18.12
129.32693|ISTEP 20. 1
131.25660|ISTEP 20. 2
134.05648|ISTEP 21. 1
153.91054|ISTEP 21. 2
153.91464|ISTEP 21. 3
[  154.418746480,5] SkiBoot skiboot-6a3a09c starting...
[  154.418750121,5] initial console log level: memory 7, driver 5
[  154.418752971,6] CPU: P9 generation processor(max 4 threads/core)
[  154.418755684,7] CPU: Boot CPU PIR is 0x0048 PVR is 0x004e0100
[  154.418758437,7] CPU: Initial max PIR set to 0x7fff
[  154.420750687,5] OPAL table: 0x300cba40 .. 0x300cbed0, branch table: 0x30002000
[  154.420758221,7] Parsing HDAT...
[  154.420760338,5] SPIRA-S found.
[  154.420764827,6] BMC #0: HW version 3, SW version 2, chip DD1.0
[  154.420770422,6] SP Family is ibm,ast2500,openbmc
[  154.420778470,7] LPC: IOPATH chip id = 0
[  154.420780399,7] LPC: FW BAR       = f0000000
[  154.420782687,7] LPC: MEM BAR      = e0000000
[  154.420784771,7] LPC: IO BAR       = d0010000
[  154.420786802,7] LPC: Internal BAR = c0012000
[  154.420803941,7] LPC UART: base addr = 3f8 (3f8) size = 1 clk = 1843200, baud = 115200
[  154.420807772,7] LPC: BT [0, 0] sms_int: 0, bmc_int: 0
[  154.421336045,5] UART: Using UART at 0x60300d00103f8
[  154.421659816,3] HDIF: Bad header format !
[  154.421703441,3] XSCOM: Bad ChipID data 1
[  154.421774779,3] HDIF: Bad header format !
[  154.421805336,3] XSCOM: Bad ChipID data 1
[  154.422357568,3] HDIF: Bad header format !
[  154.422401595,3] XSCOM: Bad ChipID data 1
[  154.422447111,3] HDIF: Bad header format !
[  154.422470409,3] CHIPTOD: Bad ChipID data 1
[  154.422497069,3] HDIF: Bad header format !
[  154.422520141,3] NX: Bad ChipID data 1
[  154.422563904,5] IOHUB: PHB4 active bridge mask fc
[  154.422667590,3] HDIF: Bad header format !
[  154.422696895,3] XSCOM: Bad ChipID data 1
[  154.422740801,3] P9: Can't find XSCOM for chip -1
[  154.422782552,4] VPD: CCIN desc not available for : P003
[  154.422831052,3] HDIF: Bad header format !
[  154.422888208,5] P9 DD1.02 detected
[  154.422914459,5] XSCOM: chip 0x0 at 0x603fc00000000 [P9N DD1.0]
[  154.422999916,5] LPC: LPC[000]: Initialized, access via MMIO @0x6030000000000
[  154.423059470,5] LPC: LPC: Default bus on chip 0x0
[  154.423142333,4] HOMER image is not reserved! Reserving
[  154.423206644,5] SLW: Enabling: stop0_lite
[  154.423308097,5] PLAT: Using virtual UART
[  154.423448722,7] LPC: LPC: Routing irq 9, policy: 0 (r=1)
[  154.423451408,7] LPC: LPC: SerIRQ 9 using route 0 targetted at OPAL
[  154.423549351,5] PLAT: Detected Witherspoon platform
[  154.423641928,0] Assert fail: core/device.c:908:id != 0xffffffff
[  154.423699955,0] Aborting!
CPU 0048 Backtrace:
 S: 0000000031d23ae0 R: 00000000300136d0   .backtrace+0x2c
 S: 0000000031d23b70 R: 0000000030018dfc   ._abort+0x4c
 S: 0000000031d23bf0 R: 0000000030018e78   .assert_fail+0x34
 S: 0000000031d23c70 R: 0000000030025908   .dt_get_chip_id+0x24
 S: 0000000031d23ce0 R: 0000000030018a70   .init_all_cpus+0x1b0
 S: 0000000031d23e30 R: 0000000030014814   .main_cpu_entry+0x404
 S: 0000000031d23f00 R: 0000000030002630   boot_entry+0x198


 ```
