### ISSUE TITLE
[ April 2017 ] Witherspoon Driver Stability Test 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#473]
Place holder for testing activities

- [x] Code update
- [x] CT run
- [x] Report analysis
- [x] Opening bug and following up

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/673/
- [x] VERSION_ID : v1.99.3-189-gb33f84c
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Thu Mar 30 21:21:56 UTC 2017 armv6l GNU/Linux

- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503


-------------------------				
Test Ran for Build 673
-------------------------		
- [x] BMC update        : PASSED 
- [x] PNOR Update       : PASSED  
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED  - 10 IPL( http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests/641/ )
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED
- [x] Power On Restore  : PASSED
- [x] Reset Reload      : FAILED ( Known limitation on witherspoon openbmc/openbmc#1322 )
- [x] Inventory         : FAILED ( Old bugs exist)( openbmc/openbmc#1357  / openbmc/openbmc#1216 )
- [x] eSEL              : FAILED ( Old bug exist )( openbmc/openbmc#1375 / openbmc/openbmc#1297 / openbmc/openbmc#1327 )
- [x] Core dumps        : FAILED ( Old bug exist )( openbmc/openbmc#1326 )
- [x] REST testing      : PASSED ( Intermittent failure openbmc/openbmc#1367 )
- [x] Error log         : PASSED
      Association       : ( Test automation code in review )
- [x] CT Run            : ( Total 132 Failed 22 Passed 110	Percent 83.3% )http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests/642/

Bug Tracker for today : 
						* None
						
- [x] Power on IPL performance : Poweron 4 minutes approx but seen few IPL taking more than 10 minutes

```

**Comment by gkeishin** [comment]
`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)   / W5 
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/675/
- [x] VERSION_ID : v1.99.3-196-gbce4eb8
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Fri Mar 31 20:33:56 UTC 2017 armv6l GNU/Linux

- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503

-------------------------				
Test Ran for Build 675
-------------------------		
- [x] BMC update        : PASSED 
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED  (10 IPL )
- [x] Host OS Booted    : YES
- [x] CT Run            : ( Total 132  fail 26	pass 106	80.3 %)
- [x] eSEL              : ( Missing Additional data https://github.com/openbmc/openbmc/issues/1297 )
- [x] Core dumps        : ( HWMON https://github.com/openbmc/openbmc/issues/1130 / IPMD https://github.com/openbmc/openbmc/issues/1326 )

Bug Tracker for today : 
				* https://github.com/openbmc/openbmc/issues/1422   ( Inventory Crashed )
						
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/676/
- [x] VERSION_ID : v1.99.3-198-g24f35b0
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Mon Apr 3 17:23:12 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503

-------------------------				
Test Ran for Build 676
-------------------------		
- [x] BMC update        : PASSED 
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) : 10 IPL (
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED
- [x] CT Run            : 
Bug Tracker for today : 
					* 
						

Notes: 
		1. System Rebooting To Perform SBE Update ( First time IPL)
		2. Core dumps IPMD/HWMON,esel/inventory are not validated explicitly until fixes are provided
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/678/
- [x] VERSION_ID : v1.99.3-203-g7a0b268
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Tue Apr 4 17:23:48 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503

-------------------------				
Test Ran for Build 678
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Run            : 

Bug Tracker for today : 

```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/688/
- [x] VERSION_ID : v1.99.4-22-ga072ab2
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Wed Apr 12 22:23:06 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503

-------------------------				
Test Ran for Build 678
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Run            : 

Bug Tracker for today : 

					   * https://github.com/openbmc/openbmc/issues/1461

```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/690/
- [x] VERSION_ID : v1.99.4-25-g330f996
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Mon Apr 17 17:23:48 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503

-------------------------				
Test Ran for Build 690
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 2 Manual ) / 10 IPL run (Watchdog error IPL istep 13.9 - Host Quiesce state)
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W50 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/694/
- [x] VERSION_ID : v1.99.4-34-gdd8a547
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Mon Apr 17 22:22:55 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.14
        op-build-v1.15-75-g986c911-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-6a3a09c
        hostboot-a58f695
        linux-4.10.6-openpower1-pef4dc3d
        petitboot-v1.4.2-pe78e1ef
        witherspoon-xml-b208e4f
        occ-4141b5f
        hostboot-binaries-82b82cd
        capp-ucode-1bb7503


-------------------------				
Test Ran for Build 690
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
                        : PASSED 10 IPL run GOOD ( http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests/707/ )
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Test           : ( Total 137  Failed 10 Passed 127  Percent 92.7 % )
                           http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests/708/

Bug Tracker for today : 
                      * None 
					   
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : W51 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/695/
- [x] VERSION_ID : v1.99.4-38-gb6e965c
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Wed Apr 19 02:25:45 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.28
        op-build-v1.15-131-gda28b74-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-de49800
        linux-4.10.7-openpower1-pd408964
        petitboot-v1.4.2-p7985f01
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-d1b1312
        capp-ucode-1bb7503
        sbe-c9fea2e-p3dffe09


-------------------------				
Test Ran for Build 695
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
                        : FAILED 10 IPL run (10th IPL failed due to Watchdog Error)
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Test           : ( Total 137  Failed 13 Passed 124  Percent 90.5 % )
                           
Bug Tracker for today : 
                      * Seen intermittent IPL failure due to Watchdog error
			* Seen intermittent failure where we are not able to poweroff onced powered on.
					   
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/697/
- [x] VERSION_ID : v1.99.4-42-g360a31b
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Wed Apr 19 22:23:36 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.28
        op-build-v1.15-131-gda28b74-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-de49800
        linux-4.10.7-openpower1-pd408964
        petitboot-v1.4.2-p7985f01
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-d1b1312
        capp-ucode-1bb7503
        sbe-c9fea2e-p3dffe09


-------------------------				
Test Ran for Build 697
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
                        : PASSED 10 IPL run 
                        : PASSED 100 IPL run
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Test           : ( Total 137  Failed 13 Passed 124  Percent 90.5 % )
- [x] Power on Restore  : PASSED ( https://gerrit.openbmc-project.xyz/#/c/3792/ )
Bug Tracker for today : 
                       
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/697/
- [x] VERSION_ID : v1.99.4-42-g360a31b
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Wed Apr 19 22:23:36 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.28
        op-build-v1.15-131-gda28b74-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-de49800
        linux-4.10.7-openpower1-pd408964
        petitboot-v1.4.2-p7985f01
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-d1b1312
        capp-ucode-1bb7503
        sbe-c9fea2e-p3dffe09


-------------------------				
Test Ran for Build 697
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
                        : PASSED 10 IPL run 
                        : PASSED 100 IPL run 
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Test           : ( Total 137  Failed 13 Passed 124  Percent 90.5 % )
- [x] Power on Restore  : PASSED ( https://gerrit.openbmc-project.xyz/#/c/3792/ )
Bug Tracker for today : 
                       
```

**Comment by gkeishin** [comment]
```*** Driver Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/699/
- [x] VERSION_ID : v1.99.4-47-g113a5c8
- [x] Kernel     : Linux witherspoon 4.7.10-6786cab8778ba96d84d89c7aec34374b5f4f1968 #1 Thu Apr 20 22:24:03 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.15_1.28
        op-build-v1.15-131-gda28b74-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-de49800
        linux-4.10.7-openpower1-pd408964
        petitboot-v1.4.2-p7985f01
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-d1b1312
        capp-ucode-1bb7503
        sbe-c9fea2e-p3dffe09
-------------------------				
Test Ran for Build 699
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED
- [x] Poweron IPL test  : PASSED ( 1 Manual ) 
                        : PASSED 10 IPL run
                        : PASSED 50 IPL run
- [x] Host OS Booted    : YES
- [x] OS reboot Test    : PASSED ( Issue reboot command on OS and it should boot back the OS )
- [x] CT Test           : ( Total 136  Failed 13 Passed 123  Percent 90.5 % )
- [x] Power on Restore  : PASSED ( https://gerrit.openbmc-project.xyz/#/c/3792/ )
Bug Tracker for today : 
                       
```
