### ISSUE TITLE
[ May 2017 ] Witherspoon Driver Stability Test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#583]
Place holder for driver and stability test

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/729/
- [x] VERSION_ID : v1.99.5-15-gc4c2bed
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 02:23:36 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 729
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED 50 IPL run ( power On / Off )
- [x] Host OS Booted    : YES
- [x] HTX Barbootme run : PASSED (1 hour) x 4 = 4 hours short HTX stress run                           
   

Bug Tracker for today : 
                       
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/732/
- [x] VERSION_ID : v1.99.5-19-g02406c9
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 19:18:11 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 732
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED 50 IPL run ( power On / Off ) 
- [x] Host OS Booted    : YES
- [x] HTX Hardbootme run : PASSED (1 hour) x 2 = 2 hours short HTX stress run   

Bug Tracker for today :
			 : https://github.com/openbmc/openbmc/issues/1577  ( IP checksum err )
                       
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/733/
- [x] VERSION_ID : v1.99.5-20-gabef2cb
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 19:18:11 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 733
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED 50 IPL run ( power On / Off ) 
- [x] Host OS Booted    : YES
- [x] HTX Hardbootme run : PASSED (1 hour) x 2 = 2 hours short HTX stress run - [x] CT Random all test : PASSED

Bug Tracker for today :
					 
                       
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/737/
- [x] VERSION_ID : v1.99.5-28-g60b4452
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 07:21:01 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 737
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : FAILED 50 IPL run ( power On / Off ) 
      (On 20th IPL hit watchdog error going to quiesce state) -> 	  Note : Dean Sanner is setting up cronus and debugging the system
- [x] Host OS Booted    : YES

Bug Tracker for today :
					 
                       : https://github.com/openbmc/openbmc/issues/1597    (WARN in ncsi_start_channel_monitor code at boot) 
	   : https://github.com/openbmc/openbmc/issues/1595    ( Software versioning restarting continously)
	  : https://github.com/openbmc/openbmc/issues/1389    ( TCP: Too many sockets openned ) - old defect
         : https://github.com/openbmc/openbmc/issues/1426    ( System going to quiesce state - Now witherspoon too)
					   
					   
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/740/
- [x] VERSION_ID : v1.99.5-33-gc133ec1
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 20:29:50 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 740
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : (36 IPL OK - failure known  DDR_PHY_RESET  issue)  50 IPL run ( power On / Off )
- [x] Host OS Booted    : YES
- [x] CT Run random all : ( 99.2 % PASSED 1 intermitent failure for host quiesce test )
- [x] HTX system test   : PASSED Short 1 hours x 2 = 2 hours run
                          
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
For Linux kernel 4.10 test

```- [x] SYSTEM     : wsbmc007  FVT system( Witherspoon - 2 Sockets - Pass 2)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build-gerrit-trigger-multi/3547/
- [x] VERSION_ID : v1.99.5-30-g67f3575
- [x] Kernel     : Linux witherspoon 4.10.5-8736136e756ec127de0bbe2c7e2de683204d4512 #1 Thu May 11 22:26:22 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------                
Stability Test Ran for Linux 4.10 Build 3547
-------------------------        
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Poweron IPL test  : PASSED 20 IPL run ( power On / Off ) 
- [x] Host OS Booted    : YES 
- [x] CT Run random all : PASSED 
                          ( 7 Failed  mostly due to system in quisce state else looks good )
- [x] BMC Reboot Test   : 50 Iteration to recreate hangs ( Repeating keyword, round 32/50) on 32nd BMC serial hung, BMC still pings , SSH refuse to connect```
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/743/
- [x] VERSION_ID : v1.99.5-40-gbaf766c
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Sat May 13 02:53:52 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 743
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : (Repeating keyword, round 44/50 )  Failed on 44th IPL quisce recovered but test automation timedout
   
- [x] Host OS Booted    : YES
- [x] CT Run random all : ( 97.7%  Total 136 Failed 3  - Known intermittent host quiesce state failure - Investigating)
   
- [x] HTX system test   : Weekend run ( 2 hours x 15 min ) x 15 = 30 hours run  
                          

Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004 / wsbmc007  FVT system( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs)  
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/744/
- [x] VERSION_ID : v1.99.5-41-gbdd2b66
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 15 16:21:31 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 744
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED (50 IPL run on wsbmc007) 
                                      PASSED (50 IPL run on wsbmc004) 
- [x] Host OS Booted    : YES
- [x] CT Run            : BMC wsbmc007 ( 99.2%  Total 140 Failed 1 ) 
                              : BMC wsbmc004 ( 100%   Total 140 Failed 0 )                           
- [x] HTX system test   : Short run ( 1 hours x 15 min ) x 1 = 1 hours run  
                         
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc007 /wsbmc004 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs )  
- [x] BUILD ID   : https://openpower.xyz/job/openbmc-build/747/
- [x] VERSION_ID : v1.99.5-48-gcc86aba
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 18 03:22:32 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 747
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED (20 IPL run) 
- [x] Host OS Booted    : YES
- [x] OS reboot test    : PASSED
- [x] CT Run            : ( 98.5 %  Total 141 Failed 2 )
- [x] HTX Run           : Short run ( 1 hour Test)
                         
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc007 /wsbmc004 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs )  
- [x] BUILD ID   : https://openpower.xyz/job/openbmc-build/748/
- [x] VERSION_ID : v1.99.5-50-gbea7ab5
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Fri May 19 12:33:48 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

-------------------------				
Stability Test Ran for Build 748
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED (20 IPL run)  
- [x] Host OS Booted    : YES
- [x] OS reboot test    : PASSED
- [x] CT Run            : ( 100 %  Total 141 Failed 0 )

**Comment by gkeishin** [comment]
`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs )  
- [x] BUILD ID   : https://openpower.xyz/job/openbmc-build/752/
- [x] VERSION_ID : v1.99.5-66-g47b348b
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 23 11:25:56 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:

IBM-witherspoon-ibm-OP9_v1.16_1.24
        op-build-v1.16-83-ge67b53c-dirty
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.6.0-rc2
        hostboot-d02273f
        linux-4.11.1-openpower1-pc11ec03
        petitboot-v1.4.2-pcb6424c
        machine-xml-e536539
        occ-8a7df03
        hostboot-binaries-d8f4ab7
        capp-ucode-9c73e9f
        sbe-d770027

-------------------------				
Stability Test Ran for Build 752
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : PASSED
- [x] Poweron IPL test  : PASSED (50 IPL run) 
- [x] Host OS Booted    : YES
- [x] OS reboot test    : PASSED
- [x] CT Run            : ( 100 %  Total 144 Failed 0 )
                                                  
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs )  
- [x] BUILD ID   : https://openpower.xyz/job/openbmc-build/762/
- [x] VERSION_ID : v1.99.5-87-ge35e620
- [x] Kernel     : Linux witherspoon 4.7.10-87950053ee336e99ea0f081695b314c962a0859c #1 Thu May 25 04:21:08 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:

IBM-witherspoon-ibm-OP9_v1.16_1.24
        op-build-v1.16-83-ge67b53c-dirty
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.6.0-rc2
        hostboot-d02273f
        linux-4.11.1-openpower1-pc11ec03
        petitboot-v1.4.2-pcb6424c
        machine-xml-e536539
        occ-8a7df03
        hostboot-binaries-d8f4ab7
        capp-ucode-9c73e9f
        sbe-d770027

-------------------------				
Stability Test Ran for Build 762
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED (CI Test 
                        : PASSED (20 IPL run)  
- [x] Host OS Booted    : YES
- [x] OS reboot test    : PASSED
- [x] CT Run            : PASSED ( 100 %  Total 144 Failed 0 )
- [x] HTX Run hardbootme: PASSED ( 1 Hour short run )
                                                  
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
```*** Driver Stabilty Build Test Outlook - Witherspoon  ***```

`MFG candidate PNOR build / Master BMC Build`
```
- [x] SYSTEM     : wsbmc004 ( Witherspoon - 2 Sockets - Pass 2 / 16 DIMMs )  
- [x] BUILD ID   : https://openpower.xyz/job/openbmc-build/763/
- [x] VERSION_ID : v1.99.5-88-gfcaf72e
- [x] Kernel     : Linux witherspoon 4.7.10-87950053ee336e99ea0f081695b314c962a0859c #1 Thu May 25 06:21:27 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION:

IBM-witherspoon-ibm-OP9_v1.16_1.24
        op-build-v1.16-83-ge67b53c-dirty
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.6.0-rc2
        hostboot-d02273f
        linux-4.11.1-openpower1-pc11ec03
        petitboot-v1.4.2-pcb6424c
        machine-xml-e536539
        occ-8a7df03
        hostboot-binaries-d8f4ab7
        capp-ucode-9c73e9f
        sbe-d770027

-------------------------				
Stability Test Ran for Build 763
-------------------------		
- [x] BMC update        : PASSED
- [x] PNOR Update       : NA
- [x] Poweron IPL test  : PASSED (CI Test )
                        : PASSED (20 IPL run)  
- [x] Host OS Booted    : YES
- [x] OS reboot test    : PASSED
- [x] CT Run            : PASSED ( 100 %  Total 144 Failed 0 ) 
        
Bug Tracker for today :
					 
```

**Comment by gkeishin** [comment]
Closing as completed for this sprint.
