### ISSUE TITLE
Sprint May 2017 - Scrum update

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#589]
**SCRUM for Week  01-05-2017 to 31-05-2017**

**Availability- Global Test Team members** 
Story Points : 8  (Automation)

- George (100%)   @gkeishin
- Sivas (50%  (Other things to take care) / 1 week vacation)    @sivassrr 
- Rahul (100%)  @rahulmah 
- Prashant(75% Automation)  @prkatti1 
- Sridevi (50% Automation)   @SrideviRamesh 
- Sweta (50% Test + automation / 50% ramping up OpenBMC training, education )  @swe12345 
- Leo (80% Automation + 20 % support Dev fixes on demand)  @lgon 
- Saqib (50%)  @saqibkh 
- Triz (30 % / Since he is winding up on development sprint work)   @mtritz 
- Gunnar (0% since still doing development sprint work)  @gtmills 
- Sathyajit (50% GUI manual execution / 50% Education )
- Stephen ( Will be joining from June 5th, doing learning/education in between)
- Alany ( 25  % )  @AlannyLopez 

-----------------------------------------------------------------------

**`GEORGE`**

**Completed:**

1.  System Test Jenkins job : https://github.com/openbmc/openbmc-test-automation/issues/582
2.  Power Restore test : https://github.com/openbmc/openbmc-test-automation/issues/576 /  https://github.com/openbmc/openbmc-test-automation/issues/575
3.  Skip list : https://github.com/openbmc/openbmc-test-automation/issues/571
4.  New REST test cases added: https://github.com/openbmc/openbmc-test-automation/issues/567
5.  HTX hardbootme : https://github.com/openbmc/openbmc-test-automation/issues/553
     Sub Task List:
     - [x] https://github.com/openbmc/openbmc-test-automation/issues/542
     - [x] https://github.com/openbmc/openbmc-test-automation/issues/558 
     - [x] https://github.com/openbmc/openbmc-test-automation/issues/561 
     - [x] https://github.com/openbmc/openbmc-test-automation/issues/565 
6.  Validate params and HTX log file https://github.com/openbmc/openbmc-test-automation/issues/580
7.  HTX Installation base code https://github.com/openbmc/openbmc-test-automation/issues/573
8.  Base Fan test code :https://github.com/openbmc/openbmc-test-automation/issues/587
9.  REST flush/ JSON verification https://github.com/openbmc/openbmc-test-automation/issues/594
10. Option for user to halt HTX on error https://github.com/openbmc/openbmc-test-automation/issues/579
11. README for skip_list https://github.com/openbmc/openbmc-test-automation/issues/614
12. Shutdown HTX if running pre setup test https://github.com/openbmc/openbmc-test-automation/issues/611 
13. Tarball enablement code update / CT  https://github.com/openbmc/openbmc-test-automation/issues/461
14. Check for Application failure CI/CT https://github.com/openbmc/openbmc-test-automation/issues/617
15. Fix CT/PNOR update failure https://gerrit.openbmc-project.xyz/#/c/4334/
16. Thermal Fan test update https://github.com/openbmc/openbmc-test-automation/issues/615
17. User pre-define MDT execution https://github.com/openbmc/openbmc-test-automation/issues/612
18. Install OPAL PRD tool https://github.com/openbmc/openbmc-test-automation/issues/613
19. PNOR Update verification  https://github.com/openbmc/openbmc-test-automation/issues/638
20. Install and address Tarball installation https://github.com/openbmc/openbmc-test-automation/issues/618 
21. Collect HTX status and log https://github.com/openbmc/openbmc-test-automation/issues/578  
22. OS IPL reboot https://github.com/openbmc/openbmc-test-automation/issues/610 (In review)
23. Inventory Fan functional state test https://github.com/openbmc/openbmc-test-automation/issues/566
24. CT Metric test run and upload https://github.com/openbmc/openbmc-test-automation/issues/648 
25. Tox configuration changed https://github.com/openbmc/openbmc-test-automation/issues/645
26. PCIE Sensor test https://github.com/openbmc/openbmc-test-automation/issues/646
27. MFG tool testing https://github.com/openbmc/openbmc-test-automation/issues/663 
28.  Network stress test : https://github.com/openbmc/openbmc-test-automation/issues/588 ( Main story )
Sub Task list:
     - [x]  BMC Network traffic payload generator test https://github.com/openbmc/openbmc-test-automation/issues/607
     - [x]  Base network stability test code https://github.com/openbmc/openbmc-test-automation/issues/608
29. Enable logging-test for elog test (https://github.com/openbmc/openbmc-test-automation/issues/662)
30. New BMC kernel 4.10 BMC device tree failure (https://github.com/openbmc/openbmc-test-automation/issues/660)
31. Driver stability test https://github.com/openbmc/openbmc-test-automation/issues/583  

	 
**In Progress / TBD:**

1. SW387409   IPL: EOFError failure during ssh login on w55 with 910.1716.20170426n ( Analysis and Discussion in progress )
2. GPU Test (Main Story) https://github.com/openbmc/openbmc-test-automation/issues/625
      Sub Tasks List:
      - [x] Resource variables and common HTX keywords https://github.com/openbmc/openbmc-test-automation/issues/633 (In review )
      - [x] dmesg / HTX error log / nvdia output (Analysis and data gathering) https://github.com/openbmc/openbmc-test-automation/issues/635 ( In review )
      - [x] GPU test case 

3. CT Metrics jenkins integration https://github.com/openbmc/openbmc-test-automation/issues/592 ( In progres ) 
4. Test for Rail Voltage (https://github.com/openbmc/openbmc-test-automation/issues/661)
5. Fix NW variable https://gerrit.openbmc-project.xyz/#/c/4451/
	  
**Blockers If any / Comments:** 

1. Enable debug tarball related stuff completely which help us to enable Errorlog / esel test . 

-----------------------------------------------------------------------

**`SIVAS`**

**Completed:**
1. GUI POC Base test https://github.com/openbmc/openbmc-test-automation/issues/407
2. Generate Test cases documentation from test suites  https://github.com/openbmc/openbmc-test-automation/issues/547
3. Phase4 - FVT Impact analysis https://github.com/openbmc/openbmc-test-automation/issues/624

**In Progress / TBD:**

1. Generated Openbmc issue files for Management to prepare status
2. Reviewed https://gerrit.openbmc-project.xyz/#/c/4183/ - XCAT 
            https://gerrit.openbmc-project.xyz/#/c/3258/
 			https://gerrit.openbmc-project.xyz/#/c/4158/
https://gerrit.openbmc-project.xyz/#/c/638
https://gerrit.openbmc-project.xyz/#/c/4202/
https://gerrit.openbmc-project.xyz/#/c/4186/
https://gerrit.openbmc-project.xyz/#/c/4190/
https://gerrit.openbmc-project.xyz/#/c/4243/
https://gerrit.openbmc-project.xyz/#/c/4185/
https://gerrit.openbmc-project.xyz/#/c/4264/

3. GUI LED toggle switch test https://github.com/openbmc/openbmc-test-automation/issues/555 ( In review ) 
4. Enable Verify FRU Properties test in CT. 
5. Enable PNOR Corruption test in poweron test code https://github.com/openbmc/openbmc-test-automation/issues/644 ( In review )

**Blockers If any / Comments:** 

-----------------------------------------------------------------------
**`PRASHANT`**

**Completed:**
1. PGood tests for IPMI https://github.com/openbmc/openbmc-test-automation/issues/520
2. Connection and login XCAT https://github.com/openbmc/openbmc-test-automation/issues/597
3. Add BMC nodes to XCAT, Power on/off https://github.com/openbmc/openbmc-test-automation/issues/620

**In Progress / TBD:**

1. Network refactoring https://github.com/openbmc/openbmc-test-automation/issues/429 
2. Ethtool automation https://github.com/openbmc/openbmc-test-automation/issues/522 
3. XCAT Testing https://github.com/openbmc/openbmc-test-automation/issues/599 ( Epic )
      - [x]  Add group nodes and get list https://github.com/openbmc/openbmc-test-automation/issues/657 (In review)

 Priority: Network, then remaining XCAT

**Blockers If any / Comments:**  
 
-----------------------------------------------------------------------

**`SRIDEVI`**

**Completed:**
1. IPMI power off/on : #521 
2. PDGB tool manual execution: #489
3.  External IPMI poweron/off https://github.com/openbmc/openbmc-test-automation/issues/593

**In Progress / TBD:**
1.  RAS TC with autoreboot option disabled : #449   ( In review - Rebase and comments to address)
2.  Lab FVT systems OS IP setup (In progress)
3.  IPMI chassis on/off test intermittent failures https://github.com/openbmc/openbmc-test-automation/issues/634 (In Progress)

**Blockers If any / Comments:** 
1. PDGB utility implementation : #577  ( Please discuss with Laksmi )
2. In band IPMI for eSEL - Takes longer time ? 
3. Move eSEL relate TC with external IPMI  - 5 TCs passing - 2 TCs are failing - (Swetha is working on it) - Use debug tarball and verify move this. Decided to keep it in extended only. 

Priority:
Enabling more TCs into CT - eSEL TCs enablement with external IPMI. 

-----------------------------------------------------------------------

**`SWETA`**

**Completed:**
1.  Errorlog test case : https://github.com/openbmc/openbmc-test-automation/issues/562

**In Progress / TBD:**
1.  Call out test : https://github.com/openbmc/openbmc-test-automation/issues/586 (In review )
2.  Release build test https://github.com/openbmc/openbmc-test-automation/issues/591 (In progress)
3.  Test cases cleanup for IPMI use cases https://github.com/openbmc/openbmc-test-automation/issues/606 (In review)
4.  Resolved Field call-out test https://github.com/openbmc/openbmc-test-automation/issues/621 (In Progress )  - Seeing an issue, will open against openbmc repository. 

**Blockers If any / Comments:** 

-----------------------------------------------------------------------

**`LEO`**

**Completed:**
1.  Display software levels/inventory and verify required tools installed   https://github.com/openbmc/openbmc-test-automation/issues/549 

**In Progress / TBD:**

1.  Verify System state https://github.com/openbmc/openbmc-test-automation/issues/550 ( In review ) - Merge soon. 

**Blockers If any / Comments:** 

Development task currently working - no Automation. ( Next sprint full development)

-----------------------------------------------------------------------

**`GUNNAR`**

After discussion, due to Development sprint work committed it is unlikely he'll do automation this sprint.

-----------------------------------------------------------------------

**`TRIZ`**

**Completed:**
1.  None

**In Progress / TBD:**
1.   CT metrics https://github.com/openbmc/openbmc-test-automation/issues/358  (In Progress)

**Blockers If any / Comments:** 

-----------------------------------------------------------------------

**`RAHUL`**

**Completed:**
1. OCC power supply redundancy and derating value TC https://github.com/openbmc/openbmc-test-automation/issues/527
2. Fix for power restore test case not getting skipped https://github.com/openbmc/openbmc-test-automation/issues/590
3. Test LED https://github.com/openbmc/openbmc-test-automation/issues/529
4. Removed working test cases from witherspoon skip list. 
5. Get URLs list https://github.com/openbmc/openbmc-test-automation/issues/410
6. Enable SOL test https://github.com/openbmc/openbmc-test-automation/issues/411

**In Progress / TBD:**

2. Test system leds of Witherspoon system. #529 (In review)  - Merged
3. Method to identify a new REST interfaces #410 (In review) - Merged
4. Turbo allowed value - #527 (In review) - Merged
5. Evaluate existing issues which are getting skipped. #303 (Need to start from 10th May) - 
6. Reset reload test update https://github.com/openbmc/openbmc-test-automation/issues/533 ( In review ) - Merged

**Blockers If any / Comments:**
1. SOL enablement #602 - Once we stop SOL we are unable to connect SOL next time in automation. Trying to resolve the problem. ( No longer blocker)
SOL TCs are in review. 

-----------------------------------------------------------------------

**`SATHYAJIT`**

**Completed:**
1.  None

**In Progress / TBD:**
1.  OpenBMC GUI manual execution https://github.com/openbmc/openbmc-test-automation/issues/596  ( In progress )

**Blockers If any / Comments:** 

-----------------------------------------------------------------------

**`SAQIB`**

**Completed:**
1.  CodeUpdate: Test for Download via TFTP  https://github.com/openbmc/openbmc-test-automation/issues/510

**In Progress / TBD:**
1.  CodeUpdate: Test for Download via TFTP  https://github.com/openbmc/openbmc-test-automation/issues/510  (In review  - got 2+, ready to merge ). 
2. CodeUpdate: Test for REST upload  https://github.com/openbmc/openbmc-test-automation/issues/511 (In review) - Saqib to talk to Gunnar, (Suspecting code stability).

572 - review. 
**Blockers If any / Comments:** 
1. CodeUpdate: Test power on https://github.com/openbmc/openbmc-test-automation/issues/512 ( Block on Dev delivery )  
2. CodeUpdate: Test corrupted image  https://github.com/openbmc/openbmc-test-automation/issues/513 ( Block on Dev delivery )
3. Based on discussion with Saqeeb, Phase 4 Code update automation can be done by him. 
( Challenge: Design keep getting changed, Same as automation code as well). 

-----------------------------------------------------------------------

**`ALANY`**

**Completed:**
1. Inventory collection https://github.com/openbmc/openbmc-test-automation/issues/554

**In Progress / TBD:**

1. Validate system configuration  https://github.com/openbmc/openbmc-test-automation/issues/626 ( In progress )  

**Blockers If any / Comments:** 

-----------------------------------------------------------------------

Notes:

Debug tarball is completed only jenkins integration pending & Sridevi can verify and move extended errorlog and esel test suite to tests.  - AI Sridevi
MFG Tool 5 TCs tested - Manually - Great - AI George (Done)
System test network will get merge this week. 

Sivas:

**Comment by SrideviRamesh** [comment]
Completed:
1. IPMI power off/on : https://github.com/openbmc/openbmc-test-automation/issues/521
2. PDGB tool manual execution: https://github.com/openbmc/openbmc-test-automation/issues/489

In Progress / TBD:
1. RAS TC with autoreboot option disabled : https://github.com/openbmc/openbmc-test-automation/issues/449

Blocker:
1. PDGB tool implementation : https://github.com/openbmc/openbmc-test-automation/issues/577

**Comment by gkeishin** [comment]
`Reviews in gerrit which needs attention`

**Comment by rahulmah** [comment]
RAHUL

Completed:
1. OCC power supply redundancy and derating value TC: https://gerrit.openbmc-project.xyz/#/c/3940/
2. Daily CT for Witherspoon, Barreleye, and Palmetto (Monday, Tuesday)
Issue logged - 
OpenBMC - 1580, 1579, 1572, 1578
OpenBMC automation - 584

In Progress / TBD:
1. Daily CT for Witherspoon, Barreleye, and Palmetto (for rest of the week)
2. Test system leds of Witherspoon system.
3. Method to identify a new REST interfaces
4. SOL enablement
6. SOL test cases
7. Turbo allowed value

Blockers If any / Comments:
1. SOL parameter TC - (Dev code in progress)

**Comment by rahulmah** [comment]
**RAHUL**

**Completed:**
1. OCC power supply redundancy and derating value TC: https://gerrit.openbmc-project.xyz/#/c/3940/
2. Daily CT for Witherspoon, Barreleye, and Palmetto (Monday, Tuesday)
Issue logged - 
OpenBMC - 1580, 1579, 1572, 1578
OpenBMC automation - 584

**In Progress / TBD:**
1. Daily CT for Witherspoon, Barreleye, and Palmetto (for rest of the week) 
2. Test system leds of Witherspoon system. (Code in review)
3. Method to identify a new REST interfaces (Code in review)
4. SOL test cases (Code in review)
5. Turbo allowed value (Code in review)
6. Evaluate existing issues which are getting skipped. (Need to start from  10th May)

**Blockers If any / Comments:**
1. SOL enablement -  Once we stop SOL we are unable to connect SOL next time in automation. Trying to resolve the problem.

**Comment by rahulmah** [comment]
**RAHUL**

Completed:
OCC power supply redundancy and derating value TC https://github.com/openbmc/openbmc-test-automation/issues/527

In Progress / TBD:
1. Daily CT for Witherspoon, Barreleye, and Palmetto - https://github.com/openbmc/openbmc-test-automation/issues/601
2. Test system leds of Witherspoon system. https://github.com/openbmc/openbmc-test-automation/issues/529
3. Method to identify a new REST interfaces https://github.com/openbmc/openbmc-test-automation/issues/410
4. SOL test cases - https://github.com/openbmc/openbmc-test-automation/issues/411
5. Turbo allowed value - https://github.com/openbmc/openbmc-test-automation/issues/527 (Code in review)
6. Fix for power restore test case not getting skipped https://github.com/openbmc/openbmc-test-automation/issues/590
7. Evaluate existing issues which are getting skipped. https://github.com/openbmc/openbmc-test-automation/issues/303 (Need to start from 10th May)

Blockers If any / Comments:
SOL enablement https://github.com/openbmc/openbmc-test-automation/issues/602 - Once we stop SOL we are unable to connect SOL next time in automation. Trying to resolve the problem.

**Comment by sivassrr** [comment]
**Action item (31 May 2017):**

- [ ] @sridevi to open issue related to wsbmc006 -   Quiesce state
- [ ] esel TCs to be reviewed - AI George, rahul, Prashanth
- [ ] XCAT test using release driver - AI Prashanth
- [ ] Security Scanning - AI Prashanth
- [ ] Need to check on OPAL Dump - AI Sivas ( May not be available for 1st GA).

**Comment by gkeishin** [comment]
Closing this sprint..
