### ISSUE TITLE
[ May 2017 ] Witherspoon Driver Stability Test (Release build)

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#591]
Please update ur status here..

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.29.119
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170509n/logs/status.html
- [x] VERSION_ID : v1.99.5-20-gabef2cb
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 9 08:50:52 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f

Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : PASSED (1 Barreleye System)
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 129 TCs, 64 Passed, 65 Failed

 Test Case Failure:
                        TCs are failing as the System is going into Quiesce state
```

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Witherspoon  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : wsbmc006
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170509n/logs/status.html
- [x] VERSION_ID : v1.99.5-20-gabef2cb
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 9 08:20:25 CDT 2017 armv6l GNU/Linux

- [x] PNOR VERSION: 
IBM-witherspoon-ibm-OP9_v1.15_1.22
        op-build-v1.15-115-ge46df0d-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0-rc3
        hostboot-3a3d65e
        linux-4.10.7-openpower1-pb32b856
        petitboot-v1.4.2-pa470686
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-46670e3
        capp-ucode-1bb7503

Test Ran

- [x] BMC update        : PASSED  ( 1 witherspoon system )
- [x] PNOR Update       : PASSED (1 Witherspoon System)
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 133 TCs, 132 Passed, 1 Failed

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.29.119
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170510n/logs/status.html
- [x] VERSION_ID : v1.99.5-21-g2933545
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Wed May 10 08:50:16 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f

Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )                  
- [x]  CT Run           : 129 TCs, 65 Passed, 64 Failed
                   TCs are failing as the system is going into Quiesce state

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Witherspoon  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : wsbmc006
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170510n/logs/status.html
- [x] VERSION_ID : v1.99.5-21-g2933545
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Wed May 10 08:20:23 CDT 2017 armv6l GNU/Linux

- [x] PNOR VERSION: 
IBM-witherspoon-ibm-OP9_v1.15_1.22
        op-build-v1.15-115-ge46df0d-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0-rc3
        hostboot-3a3d65e
        linux-4.10.7-openpower1-pb32b856
        petitboot-v1.4.2-pa470686
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-46670e3
        capp-ucode-1bb7503
Test Ran

- [x] BMC update        : PASSED  ( 1 witherspoon system )
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 ) 
- [x]  CT Run           : 132 TCs,131 passed, 1 failed

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Witherspoon  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : wsbmc006
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170511n/logs/status.html
- [x] VERSION_ID : v1.99.5-28-g60b4452
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 08:20:26 CDT 2017 armv6l GNU/Linux

- [x] PNOR VERSION: 
IBM-witherspoon-ibm-OP9_v1.15_1.22
        op-build-v1.15-115-ge46df0d-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0-rc3
        hostboot-3a3d65e
        linux-4.10.7-openpower1-pb32b856
        petitboot-v1.4.2-pa470686
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-46670e3
        capp-ucode-1bb7503
Test Ran

- [x] BMC update        : PASSED  ( 1 palmetto system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 132 TCs, 132 Passed, 0 failed


```

**Comment by swe12345** [comment]
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.30
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170511n/logs/status.html
- [x] VERSION_ID : v1.99.5-28-g60b4452
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 08:50:30 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 129 TCs, 62 Passed, 67 failed
                      
       TCs are failing as the system went into Quiesce state

```

**Comment by gkeishin** [comment]
Closed as completed for the given sprint
