### ISSUE TITLE
 RAS  Test - RR, LED, Dump, Errorlog,Error Recovery, Event Mgmt, Syslog

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#60]
RAS and manufacturing related Testing and equivalent development story is @ https://github.com/openbmc/openbmc/issues/354

**Comment by sivassrr** [comment]
RAS -SEL - https://github.com/openbmc/openbmc/issues/352
RAS - LED - https://github.com/openbmc/openbmc/issues/353

**Comment by sivassrr** [comment]
- [ ]  Need to have list of test cases associate with RAS
- [ ]  Come up with list of test cases which can automate / manual execution

- [ ]  Check for TCs need to be automate via PDBG / Cronus way / host OS way - Basic OS way of checkstop is already enabled. 

- [ ]  Create stories for automation - Automation need to be done.

**Comment by sivassrr** [comment]
@lkammath Hi Lakshmi, Are we planning to pursue BMC way of error injection etc.

**Comment by sivassrr** [comment]
During yesterday's meeting, there was emphasis on RAS especially on openbmc based boxes, So I am leaving it open.
