### ISSUE TITLE
Witherspoon Driver Stability Test (Daily build) [May 8th - May 12th]

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#601]
Witherspoon Driver Stability Test (Daily build) [May 8th - May 12th]

**Comment by rahulmah** [comment]
**8th May**

```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : wsbmc002 FVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/729
- [x] VERSION_ID : v1.99.5-15-gc4c2bed
- [x] Kernel : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 02:23:36 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

------------------------- 
Test Ran for Build 729
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/1974/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/1974/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 134 Failed 4 Passed 130 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/145/


TC failure: 
New bug logged :https://github.com/openbmc/openbmc/issues/1571 (inconsistent failure).
Other are know failures.```

**Comment by rahulmah** [comment]
**9th May**

```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : wsbmc002 FVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/732
- [x] VERSION_ID : v1.99.5-19-g02406c9
- [x] Kernel : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 19:18:11 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

------------------------- 
Test Ran for Build 732
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2008/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2008/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 133 Failed 1 Passed 132 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/150/


TC failure: Failing test case is not getting skipped with skip list (https://github.com/openbmc/openbmc-test-automation/issues/590).```

**Comment by rahulmah** [comment]
**10th May**

```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : wsbmc002 FVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/733
- [x] VERSION_ID : v1.99.5-20-gabef2cb
- [x] Kernel : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 9 11:24:06 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

------------------------- 
Test Ran for Build 733
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2041/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2041/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 133 Failed 2 Passed 131 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/152/


TC failure: 
1. Failing test case is not getting skipped with skip list. Fixed in progress - https://gerrit.openbmc-project.xyz/#/c/4151/
2. Automation failure related to FFDC - https://github.com/openbmc/openbmc-test-automation/issues/603```

**Comment by rahulmah** [comment]
11th May

```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : wsbmc002 FVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/736
- [x] VERSION_ID : v1.99.5-26-geb2af39
- [x] Kernel : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 04:21:21 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

------------------------- 
Test Ran for Build 736
------------------------- 
- [x] BMC update : Passed - 
- [x] PNOR Update : Passed - 
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 132 Failed 1 Passed 131 - 


TC failure: 
1. TC failure is inconsistent. Just hit one time.

```
```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : BarD-04 system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/736
- [x] VERSION_ID : v1.99.5-26-geb2af39
- [x] Kernel : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 04:24:43 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-barreleye-ibm-OP8_v1.15_2.4
        op-build-v1.15-96-gc612094
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-695bd89
        linux-4.10.6-openpower1-p7669d59
        petitboot-v1.4.2-p1493d08
        barreleye-xml-253622f
        occ-301b535
        hostboot-binaries-5c78ef3
        capp-ucode-1bb7503

------------------------- 
Test Ran for Build 736
------------------------- 
- [x] BMC update : Passed - 
- [x] PNOR Update : Passed - 
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 129 Failed 16 Passed 113 - 


```
```*** Driver Build Test Outlook - Palmetto ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : palm309 system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/736
- [x] VERSION_ID : v1.99.5-26-geb2af39
- [x] Kernel : Linux palmetto 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 04:25:20 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: https://openpower.xyz/job/openpower-op-build/345/distro=ubuntu,target=palmetto/artifact/images/palmetto.pnor
open-power-palmetto-922a1c1
        buildroot-211bd05
        skiboot-5.3.6
        hostboot-3ed4df7
        linux-4.4.21-openpower1-d43e553
        petitboot-v1.3.0-d1ee745
        palmetto-xml-c6f5639-d76d973
        occ-bb092e9
        hostboot-binaries-7f593a3
        capp-ucode-1bb7503
        
------------------------- 
Test Ran for Build 736
------------------------- 
- [x] BMC update : Passed - 
- [x] PNOR Update : Failed - 
- [x] Poweron IPL test : Failed - System going into quiesced state
- [x] CT Test (skip_test_witherspoon) : Total 126 Failed 30 Passed 96

TC failure: 
Test cases failure are due to system going into quiesced state.

```

**Comment by rahulmah** [comment]
12th May
```*** Driver Build Test Outlook - Witherspoon ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : wsbmc002 FVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/740
- [x] VERSION_ID : v1.99.5-33-gc133ec1
- [x] Kernel : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 20:29:50 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/witherspoon_20170501n.pnor
IBM-witherspoon-ibm-OP9_v1.16_1.3
        op-build-v1.16-35-g2bb0a83-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-c9bd42f
        linux-4.10.7-openpower1-p61306aa
        petitboot-v1.4.2-p58d71a5
        witherspoon-xml-3a7d05c
        occ-e1889e5
        hostboot-binaries-8cbbc67
        capp-ucode-1bb7503
        sbe-9b98de3-p554c410

------------------------- 
Test Ran for Build 740
------------------------- 
- [x] BMC update : Passed - 
- [x] PNOR Update : Passed - 
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 132 Failed 0 Passed 132 - 

TC failure: 
1. None

```

**Comment by gkeishin** [comment]
Closing as this is already achieved..
