### ISSUE TITLE
Automation Test Sprint Scrums

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#605]
Place holder for sprint scrums
- [x] May Sprint scrum https://github.com/openbmc/openbmc-test-automation/issues/589
- [x] June Sprint scrum https://github.com/openbmc/openbmc-test-automation/issues/669
- [x] July sprint scrum  (TBD)

**Comment by gkeishin** [comment]
Now tracking in collaborator tool
