### ISSUE TITLE
Daily Driver Stability Test (Daily build) [May 15th - May 19th]

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#630]
As discussed in the meeting, this week @swe12345 will be doing it. 

- [ ] Run daily/official driver test on Witherspoon

- [ ] Run daily/official driver test on Barreleye

- [ ] Run daily/official driver test on Palmetto

**Comment by swe12345** [comment]
18 May

```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : BarD-04(9.3.23.32)
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/747/
- [x] VERSION_ID : v1.99.5-48-gcc86aba
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 18 03:24:25 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 136 TCs, 85 Passed, 51 Failed

Bug Tracker for today:
                    * None

```

**Comment by swe12345** [comment]
18 May Witherspoon

```*** Driver build Test Outlook - Witherspoon  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : wsbmc006
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/747/
- [x] VERSION_ID : v1.99.5-48-gcc86aba
- [x] Kernel     : Linux witherspoon 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 18 03:22:32 UTC 2017 armv6l GNU/Linux
- [x] PNOR VERSION: 
IBM-witherspoon-ibm-OP9_v1.15_1.22
        op-build-v1.15-115-ge46df0d-dirty
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0-rc3
        hostboot-3a3d65e
        linux-4.10.7-openpower1-pb32b856
        petitboot-v1.4.2-pa470686
        witherspoon-xml-07ef29d
        occ-e1889e5
        hostboot-binaries-46670e3
        capp-ucode-1bb7503
Test Ran

- [x] BMC update        : PASSED  ( 1 witherspoon system )
- [x] PNOR Update       : PASSED  ( 1 witherspoon system )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 141 TCs, 140 Passed, 1 Failed

Bug Tracker for today:
                    * None

```

**Comment by swe12345** [comment]
Palmetto went into Quiesce state during code update.

**Comment by swe12345** [comment]
24 May - Barreleye


```*** Driver build Test Outlook - Palmetto  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : palm309(9.3.164.147)
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/753/
- [x] VERSION_ID : v1.99.5-67-gcf7e849
- [x] Kernel     : Linux palmetto 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 23 16:24:17 UTC 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
open-power-palmetto-v1.15-133-ga01e01e
        buildroot-2017.02-4-gc28573e
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.10.7-openpower1-p941f50a
        petitboot-v1.4.2-pda19665
        palmetto-xml-c6f5639-p292ebe6
        occ-301b535
        hostboot-binaries-d1b1312
        capp-ucode-1bb7503
Test Ran

- [x] BMC update        : PASSED  ( 1 palmetto system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 132 TCs, 82 Passed, 50 Failed

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
24 May - Barreleye

```*** Driver build Test Outlook - barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.32
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/753/
- [x] VERSION_ID : v1.99.5-67-gcf7e849
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 23 16:24:54 UTC 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 136 TCs, 97 Passed, 39 Failed

Bug Tracker for today:
                    *None

```
