### ISSUE TITLE
Automation: Secure / Trusted boot

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#651]
- [ ]  Need to have list of test cases associate with secure boot / trusted boot 
- [ ]  Come up with list of test cases which can automate / manual execution
- [ ]  Create stories for automation - Automation need to be done.

https://github.com/openbmc/openbmc/issues/1463 - Stories associate with TPM enablement on / off via BMC. 

Note: We may have to automate keeping PowerVM in mind, so that one code can be executed in 2 environment.

**Comment by sivassrr** [comment]
@kantvijay, As of now, I am not able to assign it to you.
