### ISSUE TITLE
Barreleye: Test Results

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#658]
- [ ] Please put results of Barreleye 

- [ ] Version Details of both BMC, PNOR, OS Details

- [ ] How many test passed, issue # if there is any issue opened for failed test

**Comment by sivassrr** [comment]
Please test today's driver https://openpower.xyz/job/openbmc-build/765/ and update the result.

**Comment by swe12345** [comment]
18 May Barreleye

```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : BarD-04(9.3.23.32)
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/747/
- [x] VERSION_ID : v1.99.5-48-gcc86aba
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 18 03:24:25 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 136 TCs, 85 Passed, 51 Failed

Bug Tracker for today:
                    * None

```

**Comment by swe12345** [comment]
24 May - Barreleye

```*** Driver build Test Outlook - barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.32
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/753/
- [x] VERSION_ID : v1.99.5-67-gcf7e849
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 23 16:24:54 UTC 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 136 TCs, 97 Passed, 39 Failed

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
29 May Barreleye
```*** Driver build Test Outlook - Barreleye ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.30
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/767/
- [x] VERSION_ID : v1.99.4-69-gb2ca901
- [x] Kernel     : Linux barreleye 4.10.5-8736136e756ec127de0bbe2c7e2de683204d4512 #1 Fri May 26 23:23:33 UTC 2017 armv5tejl GNU/Linux

Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 137 TCs,61 Passed, 76 failed

Bug Tracker for today:
                   *None

```

**Comment by swe12345** [comment]
9th May Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.29.119
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170509n/logs/status.html
- [x] VERSION_ID : v1.99.5-20-gabef2cb
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 9 08:50:52 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f

Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : PASSED (1 Barreleye System)
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 129 TCs, 64 Passed, 65 Failed

 Test Case Failure:
                        TCs are failing as the System is going into Quiesce state
```

**Comment by swe12345** [comment]
11th may Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.29.119
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170510n/logs/status.html
- [x] VERSION_ID : v1.99.5-21-g2933545
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Wed May 10 08:50:16 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f

Test Ran

- [x] BMC update        : PASSED  ( 1 Barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )                  
- [x]  CT Run           : 129 TCs, 65 Passed, 64 Failed
                   TCs are failing as the system is going into Quiesce state

Bug Tracker for today:
                    *None

```

**Comment by swe12345** [comment]
10th May Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.30
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170511n/logs/status.html
- [x] VERSION_ID : v1.99.5-28-g60b4452
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 08:50:30 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 129 TCs, 62 Passed, 67 failed
                      
       TCs are failing as the system went into Quiesce state

```

**Comment by swe12345** [comment]
12th May Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.30
- [x] BUILD_ID   : https://w3.austin.ibm.com//afs/austin/projects/esw/op910/Builds/910.1720.20170511n/logs/status.html
- [x] VERSION_ID : v1.99.5-28-g60b4452
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 08:50:30 CDT 2017 armv5tejl GNU/Linux

- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.16_2.1
        op-build-v1.16-51-g869393e
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.5.0
        hostboot-695bd89
        linux-4.11-openpower1-pfbc3dfb
        petitboot-v1.4.2-p5f8452b
        barreleye-xml-253622f
        occ-28f2cec
        hostboot-binaries-8cbbc67
        capp-ucode-9c73e9f
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED  ( 1 )
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 129 TCs, 62 Passed, 67 failed
                      
       TCs are failing as the system went into Quiesce state

```

**Comment by swe12345** [comment]
12 May Master Build
```*** Driver Build Test Outlook - Barreleye ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : BarD-04 system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/740
- [x] VERSION_ID : v1.99.5-33-gc133ec1
- [x] Kernel : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 20:25:27 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/barreleye_03133208.pnor
IBM-barreleye-ibm-OP8_v1.15_2.4
        op-build-v1.15-96-gc612094
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-695bd89
        linux-4.10.6-openpower1-p7669d59
        petitboot-v1.4.2-p1493d08
        barreleye-xml-253622f
        occ-301b535
        hostboot-binaries-5c78ef3
        capp-ucode-1bb7503

------------------------- 
Test Ran for Build 740
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2144/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2144/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 129 Failed 16 Passed 113 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/161/

Test failure - debugging.
```

**Comment by swe12345** [comment]
12 May Master Build

```*** Driver Build Test Outlook - Barreleye ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : BarD-04 system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/740
- [x] VERSION_ID : v1.99.5-33-gc133ec1
- [x] Kernel : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Thu May 11 20:25:27 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/barreleye_03133208.pnor
IBM-barreleye-ibm-OP8_v1.15_2.4
        op-build-v1.15-96-gc612094
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-695bd89
        linux-4.10.6-openpower1-p7669d59
        petitboot-v1.4.2-p1493d08
        barreleye-xml-253622f
        occ-301b535
        hostboot-binaries-5c78ef3
        capp-ucode-1bb7503

------------------------- 
Test Ran for Build 740
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2144/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/2144/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 129 Failed 16 Passed 113 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/161/

Test failure - debugging.
```

**Comment by swe12345** [comment]
8th May Barreleye Master Build
```*** Driver Build Test Outlook - Barreleye ***```

`MFG candidate PNOR build / Master BMC Build`
```- [x] SYSTEM : BarreleyePVT system 
- [x] BUILD_ID : https://openpower.xyz/job/openbmc-build/729
- [x] VERSION_ID : v1.99.5-15-gc4c2bed
- [x] Kernel : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Mon May 8 02:23:42 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: /esw/san2/rahulmah/PNOR/barreleye_03133208.pnor
IBM-barreleye-ibm-OP8_v1.15_2.4
        op-build-v1.15-96-gc612094
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-695bd89
        linux-4.10.6-openpower1-p7669d59
        petitboot-v1.4.2-p1493d08
        barreleye-xml-253622f
        occ-301b535
        hostboot-binaries-5c78ef3
        capp-ucode-1bb7503

------------------------- 
Test Ran for Build 729
------------------------- 
- [x] BMC update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/1975/
- [x] PNOR Update : Passed - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/1975/
- [x] Poweron IPL test : PASSED
- [x] CT Test (skip_test_witherspoon) : Total 127 Failed 67 Passed 60 - http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/run-hardware-tests_CT/146/robot/report/log.html#s1-s17-t2


TC failure: 
Test cases failure are due to system going into quiesced state```

**Comment by swe12345** [comment]
4th May Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```- [x] SYSTEM     : 9.3.29.119
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/721
- [x] VERSION_ID : v1.99.4-83-g934587b
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 2 17:22:42 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: 
IBM-barreleye-ibm-OP8_v1.15_2.4
        op-build-v1.15-96-gc612094
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-695bd89
        linux-4.10.6-openpower1-p7669d59
        petitboot-v1.4.2-p1493d08
        barreleye-xml-253622f
        occ-301b535
        hostboot-binaries-5c78ef3
        capp-ucode-1bb7503

Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : PASSED
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 172 TC, 106 passed, 66 failed
        Known Issue: https://github.com/openbmc/openbmc/issues/1367, many tests failed because of this.
Bug Tracker for today:
                   *None```

**Comment by swe12345** [comment]
3rd May Barreleye
```*** Driver build Test Outlook - Barreleye  ***```
` PNOR / Master Build BMC  Test`
```- [x] SYSTEM     : 9.3.23.30
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/721
- [x] VERSION_ID : v1.99.4-83-g934587b
- [x] Kernel     : Linux barreleye 4.7.10-15c30d4deb0a01f398230395dc0d9af4be92d856 #1 Tue May 2 17:22:42 UTC 2017 armv5tejl GNU/Linux
- [x] PNOR VERSION: 
open-power-barreleye-v1.15-4-g333c9b6
        buildroot-2017.02-4-gc28573e
        skiboot-5.4.3
        hostboot-fe5c556
        linux-4.10.1-openpower1-p3080f75
        petitboot-v1.4.1-pb89a0fa
        barreleye-xml-253622f
        occ-f018940
        hostboot-binaries-4b44090
        capp-ucode-1bb7503
Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 119 TC, 62 passed, 57 failed
        Known Issue: https://github.com/openbmc/openbmc/issues/1426
Bug Tracker for today:
                   *None```

**Comment by swe12345** [comment]
30th May Barreleye
```*** Driver build Test Outlook - Barreleye ***```
` PNOR / Master Build BMC  Test`
```- [x] SYSTEM     : 9.3.23.32
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/768/
- [x] VERSION_ID : v1.99.6-18-g221ab78
- [x] Kernel     : Linux barreleye 4.10.5-8736136e756ec127de0bbe2c7e2de683204d4512 #1 Tue May 30 03:23:17 UTC 2017 armv5tejl GNU/Linux

Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 137 TCs,73 Passed, 64 failed
             System went into Quiesce state
Bug Tracker for today:
                   *None```

**Comment by swe12345** [comment]
31st May Barreleye


```*** Driver build Test Outlook - Barreleye ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.32
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/771/
- [x] VERSION_ID : v1.99.6-19-gab8de5b
- [x] Kernel     : Linux barreleye 4.10.5-8736136e756ec127de0bbe2c7e2de683204d4512 #1 Tue May 30 08:50:34 CDT 2017 armv5tejl GNU/Linux

Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 137 TCs,73 Passed, 64 failed

Bug Tracker for today:
                   *None

```

**Comment by swe12345** [comment]
28 May Barreleye Loop Test

```*** Driver build Test Outlook - Barreleye ***```
` PNOR / Master Build BMC  Test`
```
- [x] SYSTEM     : 9.3.23.32
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/766/
- [x] VERSION_ID : v1.99.6-4-g7f01f21

Test Ran

- [x] BMC update        : PASSED  ( 1 barreleye system )
- [x] PNOR Update       : NA
- [x] Reboot to Standby : PASSED  ( 1 ) 
- [x] Poweron IPL test  : PASSED  ( 1 )
- [x]  CT Run           : 1580 TCs, 289 Passed, 1291 failed

Bug Tracker for today:
                   *None

```

**Comment by gkeishin** [comment]
Closed for the given sprint
