### ISSUE TITLE
Frequency Test:  Processor / GPU / Bus Speed 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#764]
- [ ] Check for Processor Frequency    (Turbo / Non -Turbo mode )

- [ ] Check for GPU Frequency

- [ ] Check for Bus Speed

**Comment by sivassrr** [comment]
@ssombar , Please work with @gkeishin on this. This need to go in both FVT and systest bucket, I guess.

**Comment by ssombar** [comment]
RE: GPU frequency 
I could be wrong but I think  "lshw" on Ubuntu currently shows only NVIDIA's pci bus speed. 
  product: NVIDIA Corporation   clock: 33MHz   Width:  64 bits
This article shows some handy commands but none of them work on our  Witherspoon with GPU
 https://askubuntu.com/questions/5417/how-to-get-the-gpu-info

**Comment by ssombar** [comment]
Which Bus Speed do we need to know??   There are several Busses

**Comment by ssombar** [comment]
Processor frequency significantly varies with OCC/tmpd/ondemand-daemon.  On an idle system, you can do an initial OS scan or lshw   then immediately do another   lshw or scan,  and get different processor speeds.

**Comment by gkeishin** [comment]
Probably Karl/Trantow can help us out here.. @ssombar

**Comment by ssombar** [comment]
I would expect Manufacturing to testing these items.   But I agree its a good to check them

**Comment by ssombar** [comment]
Steven Sombar:
 hi Martha,    on Witherspoon do you know if there's a command to set  turbo/non turbo processor speed? 
Martha Broyles:  you have to do it from the OS 
 This command will show you the frequency range and what frequency you 
 are currently running:  cpupower frequency-info 
To set a static frequency example setting to 2.0GHz:    cpupower frequency-set -f 2000000 
Steven Sombar/Austin/Contr/IBM: 
 So there's no  "turbo"   or "non_turbo" speed  but a choice of  the available frequency steps instead? 
Martha Broyles: 
 You can set different on-demand governor policies i.e. equivalent of dynamic power save modes. 
 With Linux, Linux controls the frequency so you get their "modes" 
Steven Sombar/Austin/Contr/IBM: 
  ok,  I set it with  cpupower frequency-set    and read it back with cpupower  frequency-info 
Martha Broyles:  yep

**Comment by ssombar** [comment]
Karl Solie:  I am thinking that the bus we want to look at is likely the NVLink2 bus/link.

**Comment by gkeishin** [comment]
Let's start with 

Check for Processor Frequency (Turbo / Non -Turbo mode )

while we wait for more clarity on the GPU speed and bus link.. 

@ssombar

**Comment by ssombar** [comment]
Initial Design for Speed Test.   
  must be done from OS. 
  1.  Disable ondemand power management govenor.
  2.  Determine how many processors there are with
       lshw -C processor.  Save their current speed ("size") settings.
  3.  Set minimum speed of all processors (usually to 2 GHz), with 
       cpupower -c all  frequency-set  -f 2000000
  4.  Check speed of all processors with lshw -C processor, 
       should be "size: 200x MHz" 
  5.  Repeat steps 3 and 4 but for 3 GHz
  6.  Return processors to their original speeds reported in step 2.
  7.  Re-enable ondemand govenor

**Comment by ssombar** [comment]
Cannot find a system on AES that has cpupower utility installed, and
Installation of cpupower tool on Ubuntu is blocked by
 https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1696375

**Comment by sivassrr** [comment]
Have updated CPU / Bus frequency info. @ssombar

**Comment by sivassrr** [comment]
@ssombar Pls refer this https://github.com/openbmc/openbmc/issues/1530 , https://github.com/openbmc/openbmc/issues/1213

Use/explore  cat /proc/cpuinfo,  /proc/bus ..

**Comment by sivassrr** [comment]
@ssombar we can do from petitboot itself. Not depend on OS

**Comment by gkeishin** [comment]
@sivassrr The thing is if we need it to automate it,  we need to see what can we find from OS and continue. We don't have the petitboot automation at the moment.

**Comment by ssombar** [comment]
I think we need a more detailed description/design of what is needed here before we can proceed.

**Comment by ssombar** [comment]
Seeing a fail when I manually step through the test scenario for processor turbo-  and non-turbo speeds,

**Comment by ssombar** [comment]
Processor speed check:  https://gerrit.openbmc-project.xyz/8476

GPU speeds, temperature, and power were completed under https://github.com/openbmc/openbmc-test-automation/issues/637
